### ISSUE TITLE
Missing length on Strings for MySQL

### ISSUE THREAD

**Issue by RobertBeilich** [meraki-analytics/cassiopeia-datastores#10]
MySQL requires a length for varchar and sqlalchemy does not seem to provide a default, so it's needed to provide a length for **all** strings

needs to be fixed here:

* https://github.com/meraki-analytics/cassiopeia-datastores/blob/master/cassiopeia-sqlstore/cassiopeia_sqlstore/match.py#L38-L39
* https://github.com/meraki-analytics/cassiopeia-datastores/blob/master/cassiopeia-sqlstore/cassiopeia_sqlstore/match.py#L205

or am I missing something?

**Comment by Satrium** [comment]
Sorry for the late response. I'm currently looking at this issue.

There seems to be the same problem for Numeric keys here:
https://github.com/meraki-analytics/cassiopeia-datastores/blob/2fd4d6840590008fe2ca432841eddc84b6b601c8/cassiopeia-sqlstore/cassiopeia_sqlstore/match.py#L19-L22
as the default values don't seem to fit and lead to truncated values.

I will test the sqlstore on mysql a bit more and see if more changes need to be made for it to function properly. I've only tested it with postgresql yet. Will open a PR later today with all nessesary changes.
If you find any more problems while using mysql let me know.

**Comment by Satrium** [comment]
Just opened the PR. It includes various small fixes for mysql.
You can install it after it got merged directly from github:
`pip install -e 'git+https://github.com/meraki-analytics/cassiopeia-datastores#egg=cassiopeia-sqlstore&subdirectory=cassiopeia-sqlstore'`
If you find any more bugs, let me know.

**Comment by RobertBeilich** [comment]
thanks, it's working now (=
